title: "转生为硅基生命"
subtitle: "Version 2.0"
teaser: "images/500x300.jpg"
logo: "images/88x88.png"
email: "1637504800@qq.com"
name: "John Fan"
description: "Stop useless effort and dive into what you are really interested in!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnfan12.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: john
github_username:  johnfan12
repository: "johnfan12/Forsitecomments"

collections:
  study:
    output: true
    permalink: /:collection/:path/

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOK9B18w"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOK9B1884Cb9Gj"
    discussion_term      : "pathname" 
    reactions_enabled    : '1'
    theme                : "light"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: Yifan Wu
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      words_per_minute: 180
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
  # _study
  - scope:
      path: ""
      type: study
    values:
      layout: single
      author: Yifan Wu
      author_profile: true
      comments: true
      share: true
      related: true
      show_date: true

minimal_mistakes_skin: "dirt"
locale: "zh"
date_format: "%Y-%m-%d"
search: true
paginate: 5
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include:
  - _pages
