title: Share visions
subtitle: "stay calm"
name: "Fan"
url: johnfan12.github.io
email: your-email@example.com
repository: "johnfan12/johnfan12.github.io"
teaser: /assets/images/kawaii.png
logo: "/assets/images/kawaii.png"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
author_profile: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true 
plugins:
  - jekyll-feed
  - jekyll-include-cache
author:
  name     : "John Fan"
  avatar   : "/assets/images/header.jpg"
  bio      : "A student. To record my feelings, my ideas."
  location : "CA, USA"
header:
  image: ”/assets/images/header.jpg“
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
